name: mongo_dart
version: 0.8.0-1.0.beta
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!
homepage: https://github.com/mongo-dart/mongo_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bson: ^2.0.0-1.0.beta
  crypto: ^3.0.0
  logging: ^1.0.0
  mongo_dart_query: ^2.0.0-1.0.beta
  collection: ^1.15.0
  path: ^1.8.0
  pool: ^1.5.0
  basic_utils: ^4.2.0
  decimal: ^2.2.0
  uuid: ^3.0.0
  sasl_scram: ^0.1.0
  vy_string_utils: ^0.4.0
    
dev_dependencies:
  test: ^1.16.4
  lints: ^1.0.1

false_secrets:
 - /test/certificates_for_testing/*.key
 - /test/certificates_for_testing/*.pem
