name: mongo_dart
version: 0.1.16
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ted Sander <ted@tedsander.com>
description: MongoDB driver for Dart
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  bson: any
  args: any
  logging: any
  mongo_dart_query:
    path: ../mongo_dart_query
  meta: any
dev_dependencies:
  unittest: any
