name: mongo_dart
version: 0.11.0
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!
homepage: https://github.com/mongo-dart/mongo_dart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bson: ^5.0.3
  crypto: ^3.0.3
  fixnum: ^1.1.0
  logging: ^1.2.0
  mongo_dart_query: ^5.0.0
  collection: ^1.18.0
  path: ^1.8.3
  pool: ^1.5.1
  basic_utils: ^5.7.0
  decimal: ^2.3.3
  uuid: ^4.3.3
  sasl_scram: ^0.1.1
  vy_string_utils: ^0.4.5
    
dev_dependencies:
  test: ^1.16.4
  lints: ^3.0.0

false_secrets:
 - /test/certificates_for_testing/*.key
 - /test/certificates_for_testing/*.pem
