name: mongo_dart
description: MongoDB driver for Dart
version: 0.0.3
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  unittest:
    sdk: unittest
  args:
    sdk: args  
  log4dart: ">=1.0.0 <2.0.0"
