name: mongo_dart
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ted Sander <ted@tedsander.com>
- Paul Evans <pevans@sonardesign.com>
version: 0.1.37
homepage: https://github.com/vadimtsushko/mongo_dart
description: MongoDB driver for Dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  bson: any
  crypto: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  mongo_dart_query: any
dev_dependencies:
  hop: any
  unittest: '>=0.9.0 <0.10.0'
