name: mongo_dart
description: MongoDB driver for Dart
version: 0.0.7
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  unittest:
    sdk: unittest
  args:
    sdk: args
  logging:
    sdk: logging
  meta:
    sdk: meta    