name: mongo_dart
description: MongoDB driver for Dart
version: 0.0.4
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  unittest:
    sdk: unittest
  args:
    sdk: args  
  log4dart: any
