name: mongo_dart
description: MongoDB driver for Dart
version: 0.0.9-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
 unittest: any
 args: any
 logging: any
 meta: any